const EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS'
const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED'
const INVALID_JWT_TOKEN = 'INVALID_JWT_TOKEN'
const USER_NOT_FOUND = 'USER_NOT_FOUND'
const FAVORITE_EXISTS = 'FAVORITE_EXISTS'
const ID_IS_NOT_VALID = 'ID_IS_NOT_VALID'

module.exports = {
    EMAIL_ALREADY_EXISTS,
    AUTHENTICATION_FAILED,
    INVALID_JWT_TOKEN,
    USER_NOT_FOUND,
    FAVORITE_EXISTS,
    ID_IS_NOT_VALID
}