const EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS'
const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED'
const INVALID_JWT_TOKEN = 'INVALID_JWT_TOKEN'
const USER_NOT_FOUND = 'USER_NOT_FOUND'

module.exports = {
    EMAIL_ALREADY_EXISTS,
    AUTHENTICATION_FAILED,
    INVALID_JWT_TOKEN,
    USER_NOT_FOUND
}